spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aidev
    username: root
    password: asg159200!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
server:
  port: 9090